### PR TITLE
Add data stream for AWARE Micro server

### PR DESCRIPTION
**Pull request by shaabans**
Add support for the slightly different format of tables written by the AWARE Micro server (https://github.com/denzilferreira/aware-micro), where sensor data is contained within a `data` column in each table.

### CODE REVIEW

**Comment by JulioV** [comment]
Thanks a lot! It's great to see this was an easy fix

**Comment by JulioV** [comment]
Sounds good! If you don't find any issues in the next couple of weeks can you let us know so we release it in a new version, please? Thanks!

**Comment by shaabans** [comment]
@JulioV it seems like this has been working well after a week of testing. Email me if you'd like to join the test, which we'll be running for a few more weeks before the trial. If so, I can send you your RAPIDS results for a sniff test.

**Comment by JulioV** [comment]
Thanks Sam, that's ok we can release it, if we find any bugs we can always push a hot fix. Thanks a lot!

@Meng6 can you create the release whenever you have time please?

**Pull request merged**
